### ISSUE TITLE
Leyenda Verificación de Admin de sitio web duplicada

### ISSUE THREAD

**Issue by bronxi47** [constata-eu/constata-client#9]
Al ejecutar dos veces verify-website de un mismo sitio web, y luego website-verifications para verificarlo, se duplica la leyenda  "Web: Verificamos que el firmante administra la web https://sitio.web" en el certificado de sello de tiempo.

Environment: production
SO: GNU/Linux y MS Windows.

**Comment by nubis** [comment]
No me queda claro si es un tema cosmético, o que por algún motivo se crearon 2 pedidos de certificación de la misma web en el backend y el front-end está mostrando ambos.

Cual fue el dominio (así lo encontramos más rápido en prod).

**Comment by nubis** [comment]
Ahh, desde el admin se deberían poder ver los endorsements así los podés buscar directamente @LuchoLeonel

**Comment by bronxi47** [comment]
> No me queda claro si es un tema cosmético, o que por algún motivo se crearon 2 pedidos de certificación de la misma web en el backend y el front-end está mostrando ambos.
> 
> Cual fue el dominio (así lo encontramos más rápido en prod).

La web es www.camaramadrid.es
Person_id: 65.

**Comment by nubis** [comment]
Tenemos 2 problemas con esto. Además de permitirse intentar verificar el mismo dominio más de una vez para la misma persona, estamos mostrando como endorsement correcto los casos donde el dominio falló en verificarse. Le borré la verificación 'fallida' a la cámara, así que para ellos desde ya solo se va a mostrar una verificación. Los bugs voy a arrglarlos y se cierran con este issue.
